services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d url_shortener"]
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrator:
    image: migrate/migrate:v4.18.2
    command: ["-path", "/migrations", "-database", "postgres://root:secret@postgres:5432/url_shortener?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    restart: on-failure
    environment:
      - APP_ENV=local
      - SERVER_PORT=8080
      - BASE_URL=http://localhost:8080
      - DATABASE_URL=postgres://root:secret@postgres:5432/url_shortener?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=PgK13YiT0UpoxxpbusZJbnm85yNBEmdfcPCL4GLIxkT
      - JWT_TTL=24h
      - CORS_ORIGINS=http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  postgres_data:
