// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/katatrina/url-shortener/internal/cache"
	model "github.com/katatrina/url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockURLRepository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockURLRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockURLRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockURLRepository) Create(ctx context.Context, url model.URL) (*model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, url)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLRepositoryMockRecorder) Create(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLRepository)(nil).Create), ctx, url)
}

// Delete mocks base method.
func (m *MockURLRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLRepository)(nil).Delete), ctx, id)
}

// FindByShortCode mocks base method.
func (m *MockURLRepository) FindByShortCode(ctx context.Context, shortCode string) (*model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockURLRepositoryMockRecorder) FindByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockURLRepository)(nil).FindByShortCode), ctx, shortCode)
}

// ListByUserID mocks base method.
func (m *MockURLRepository) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockURLRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockURLRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// ShortCodeExists mocks base method.
func (m *MockURLRepository) ShortCodeExists(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortCodeExists", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortCodeExists indicates an expected call of ShortCodeExists.
func (mr *MockURLRepositoryMockRecorder) ShortCodeExists(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortCodeExists", reflect.TypeOf((*MockURLRepository)(nil).ShortCodeExists), ctx, shortCode)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// MockURLCacheRepository is a mock of URLCacheRepository interface.
type MockURLCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockURLCacheRepositoryMockRecorder is the mock recorder for MockURLCacheRepository.
type MockURLCacheRepositoryMockRecorder struct {
	mock *MockURLCacheRepository
}

// NewMockURLCacheRepository creates a new mock instance.
func NewMockURLCacheRepository(ctrl *gomock.Controller) *MockURLCacheRepository {
	mock := &MockURLCacheRepository{ctrl: ctrl}
	mock.recorder = &MockURLCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCacheRepository) EXPECT() *MockURLCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURLCacheRepository) Delete(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLCacheRepositoryMockRecorder) Delete(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLCacheRepository)(nil).Delete), ctx, shortCode)
}

// Get mocks base method.
func (m *MockURLCacheRepository) Get(ctx context.Context, shortCode string) (*cache.CachedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortCode)
	ret0, _ := ret[0].(*cache.CachedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLCacheRepositoryMockRecorder) Get(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLCacheRepository)(nil).Get), ctx, shortCode)
}

// Set mocks base method.
func (m *MockURLCacheRepository) Set(ctx context.Context, shortCode string, cached *cache.CachedURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shortCode, cached)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockURLCacheRepositoryMockRecorder) Set(ctx, shortCode, cached any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockURLCacheRepository)(nil).Set), ctx, shortCode, cached)
}

// MockClickEventQueryRepository is a mock of ClickEventQueryRepository interface.
type MockClickEventQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockClickEventQueryRepositoryMockRecorder is the mock recorder for MockClickEventQueryRepository.
type MockClickEventQueryRepositoryMockRecorder struct {
	mock *MockClickEventQueryRepository
}

// NewMockClickEventQueryRepository creates a new mock instance.
func NewMockClickEventQueryRepository(ctrl *gomock.Controller) *MockClickEventQueryRepository {
	mock := &MockClickEventQueryRepository{ctrl: ctrl}
	mock.recorder = &MockClickEventQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventQueryRepository) EXPECT() *MockClickEventQueryRepositoryMockRecorder {
	return m.recorder
}

// GetTopCountries mocks base method.
func (m *MockClickEventQueryRepository) GetTopCountries(ctx context.Context, urlID string, from, to time.Time, limit int) ([]model.CountryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCountries", ctx, urlID, from, to, limit)
	ret0, _ := ret[0].([]model.CountryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCountries indicates an expected call of GetTopCountries.
func (mr *MockClickEventQueryRepositoryMockRecorder) GetTopCountries(ctx, urlID, from, to, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCountries", reflect.TypeOf((*MockClickEventQueryRepository)(nil).GetTopCountries), ctx, urlID, from, to, limit)
}

// GetTopReferrers mocks base method.
func (m *MockClickEventQueryRepository) GetTopReferrers(ctx context.Context, urlID string, from, to time.Time, limit int) ([]model.ReferrerStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopReferrers", ctx, urlID, from, to, limit)
	ret0, _ := ret[0].([]model.ReferrerStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopReferrers indicates an expected call of GetTopReferrers.
func (mr *MockClickEventQueryRepositoryMockRecorder) GetTopReferrers(ctx, urlID, from, to, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopReferrers", reflect.TypeOf((*MockClickEventQueryRepository)(nil).GetTopReferrers), ctx, urlID, from, to, limit)
}

// MockURLStatsQueryRepository is a mock of URLStatsQueryRepository interface.
type MockURLStatsQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLStatsQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockURLStatsQueryRepositoryMockRecorder is the mock recorder for MockURLStatsQueryRepository.
type MockURLStatsQueryRepositoryMockRecorder struct {
	mock *MockURLStatsQueryRepository
}

// NewMockURLStatsQueryRepository creates a new mock instance.
func NewMockURLStatsQueryRepository(ctrl *gomock.Controller) *MockURLStatsQueryRepository {
	mock := &MockURLStatsQueryRepository{ctrl: ctrl}
	mock.recorder = &MockURLStatsQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStatsQueryRepository) EXPECT() *MockURLStatsQueryRepositoryMockRecorder {
	return m.recorder
}

// GetDailyStats mocks base method.
func (m *MockURLStatsQueryRepository) GetDailyStats(ctx context.Context, urlID string, from, to time.Time) ([]model.DailyStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStats", ctx, urlID, from, to)
	ret0, _ := ret[0].([]model.DailyStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStats indicates an expected call of GetDailyStats.
func (mr *MockURLStatsQueryRepositoryMockRecorder) GetDailyStats(ctx, urlID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStats", reflect.TypeOf((*MockURLStatsQueryRepository)(nil).GetDailyStats), ctx, urlID, from, to)
}

// MockClickCollector is a mock of ClickCollector interface.
type MockClickCollector struct {
	ctrl     *gomock.Controller
	recorder *MockClickCollectorMockRecorder
	isgomock struct{}
}

// MockClickCollectorMockRecorder is the mock recorder for MockClickCollector.
type MockClickCollectorMockRecorder struct {
	mock *MockClickCollector
}

// NewMockClickCollector creates a new mock instance.
func NewMockClickCollector(ctrl *gomock.Controller) *MockClickCollector {
	mock := &MockClickCollector{ctrl: ctrl}
	mock.recorder = &MockClickCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickCollector) EXPECT() *MockClickCollectorMockRecorder {
	return m.recorder
}

// Track mocks base method.
func (m *MockClickCollector) Track(urlID string, meta model.ClickMeta) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Track", urlID, meta)
}

// Track indicates an expected call of Track.
func (mr *MockClickCollectorMockRecorder) Track(urlID, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockClickCollector)(nil).Track), urlID, meta)
}

// MocktokenCreator is a mock of tokenCreator interface.
type MocktokenCreator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenCreatorMockRecorder
	isgomock struct{}
}

// MocktokenCreatorMockRecorder is the mock recorder for MocktokenCreator.
type MocktokenCreatorMockRecorder struct {
	mock *MocktokenCreator
}

// NewMocktokenCreator creates a new mock instance.
func NewMocktokenCreator(ctrl *gomock.Controller) *MocktokenCreator {
	mock := &MocktokenCreator{ctrl: ctrl}
	mock.recorder = &MocktokenCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenCreator) EXPECT() *MocktokenCreatorMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MocktokenCreator) CreateToken(userID string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MocktokenCreatorMockRecorder) CreateToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MocktokenCreator)(nil).CreateToken), userID)
}
