// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katatrina/url-shortener/internal/service (interfaces: URLStatsQueryRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_url_stats_query_repository.go -package mock github.com/katatrina/url-shortener/internal/service URLStatsQueryRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/katatrina/url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLStatsQueryRepository is a mock of URLStatsQueryRepository interface.
type MockURLStatsQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLStatsQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockURLStatsQueryRepositoryMockRecorder is the mock recorder for MockURLStatsQueryRepository.
type MockURLStatsQueryRepositoryMockRecorder struct {
	mock *MockURLStatsQueryRepository
}

// NewMockURLStatsQueryRepository creates a new mock instance.
func NewMockURLStatsQueryRepository(ctrl *gomock.Controller) *MockURLStatsQueryRepository {
	mock := &MockURLStatsQueryRepository{ctrl: ctrl}
	mock.recorder = &MockURLStatsQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStatsQueryRepository) EXPECT() *MockURLStatsQueryRepositoryMockRecorder {
	return m.recorder
}

// GetDailyStats mocks base method.
func (m *MockURLStatsQueryRepository) GetDailyStats(ctx context.Context, urlID string, from, to time.Time) ([]model.DailyStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStats", ctx, urlID, from, to)
	ret0, _ := ret[0].([]model.DailyStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStats indicates an expected call of GetDailyStats.
func (mr *MockURLStatsQueryRepositoryMockRecorder) GetDailyStats(ctx, urlID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStats", reflect.TypeOf((*MockURLStatsQueryRepository)(nil).GetDailyStats), ctx, urlID, from, to)
}
