// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katatrina/url-shortener/internal/service (interfaces: URLCacheRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_url_cache.go -package mock github.com/katatrina/url-shortener/internal/service URLCacheRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	cache "github.com/katatrina/url-shortener/internal/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockURLCacheRepository is a mock of URLCacheRepository interface.
type MockURLCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockURLCacheRepositoryMockRecorder is the mock recorder for MockURLCacheRepository.
type MockURLCacheRepositoryMockRecorder struct {
	mock *MockURLCacheRepository
}

// NewMockURLCacheRepository creates a new mock instance.
func NewMockURLCacheRepository(ctrl *gomock.Controller) *MockURLCacheRepository {
	mock := &MockURLCacheRepository{ctrl: ctrl}
	mock.recorder = &MockURLCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCacheRepository) EXPECT() *MockURLCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURLCacheRepository) Delete(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLCacheRepositoryMockRecorder) Delete(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLCacheRepository)(nil).Delete), ctx, shortCode)
}

// Get mocks base method.
func (m *MockURLCacheRepository) Get(ctx context.Context, shortCode string) (*cache.CachedURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortCode)
	ret0, _ := ret[0].(*cache.CachedURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLCacheRepositoryMockRecorder) Get(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLCacheRepository)(nil).Get), ctx, shortCode)
}

// Set mocks base method.
func (m *MockURLCacheRepository) Set(ctx context.Context, shortCode string, cached *cache.CachedURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shortCode, cached)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockURLCacheRepositoryMockRecorder) Set(ctx, shortCode, cached any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockURLCacheRepository)(nil).Set), ctx, shortCode, cached)
}
