// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katatrina/url-shortener/internal/service (interfaces: ClickCollector)
//
// Generated by this command:
//
//	mockgen -destination mock_click_collector.go -package mock github.com/katatrina/url-shortener/internal/service ClickCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	analytics "github.com/katatrina/url-shortener/internal/analytics"
	gomock "go.uber.org/mock/gomock"
)

// MockClickCollector is a mock of ClickCollector interface.
type MockClickCollector struct {
	ctrl     *gomock.Controller
	recorder *MockClickCollectorMockRecorder
	isgomock struct{}
}

// MockClickCollectorMockRecorder is the mock recorder for MockClickCollector.
type MockClickCollectorMockRecorder struct {
	mock *MockClickCollector
}

// NewMockClickCollector creates a new mock instance.
func NewMockClickCollector(ctrl *gomock.Controller) *MockClickCollector {
	mock := &MockClickCollector{ctrl: ctrl}
	mock.recorder = &MockClickCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickCollector) EXPECT() *MockClickCollectorMockRecorder {
	return m.recorder
}

// Track mocks base method.
func (m *MockClickCollector) Track(event analytics.ClickEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Track", event)
}

// Track indicates an expected call of Track.
func (mr *MockClickCollectorMockRecorder) Track(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockClickCollector)(nil).Track), event)
}
