// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katatrina/url-shortener/internal/service (interfaces: ClickEventQueryRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_click_event_query_repository.go -package mock github.com/katatrina/url-shortener/internal/service ClickEventQueryRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/katatrina/url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockClickEventQueryRepository is a mock of ClickEventQueryRepository interface.
type MockClickEventQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickEventQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockClickEventQueryRepositoryMockRecorder is the mock recorder for MockClickEventQueryRepository.
type MockClickEventQueryRepositoryMockRecorder struct {
	mock *MockClickEventQueryRepository
}

// NewMockClickEventQueryRepository creates a new mock instance.
func NewMockClickEventQueryRepository(ctrl *gomock.Controller) *MockClickEventQueryRepository {
	mock := &MockClickEventQueryRepository{ctrl: ctrl}
	mock.recorder = &MockClickEventQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickEventQueryRepository) EXPECT() *MockClickEventQueryRepositoryMockRecorder {
	return m.recorder
}

// GetTopCountries mocks base method.
func (m *MockClickEventQueryRepository) GetTopCountries(ctx context.Context, urlID string, limit int) ([]model.CountryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCountries", ctx, urlID, limit)
	ret0, _ := ret[0].([]model.CountryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCountries indicates an expected call of GetTopCountries.
func (mr *MockClickEventQueryRepositoryMockRecorder) GetTopCountries(ctx, urlID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCountries", reflect.TypeOf((*MockClickEventQueryRepository)(nil).GetTopCountries), ctx, urlID, limit)
}

// GetTopReferrers mocks base method.
func (m *MockClickEventQueryRepository) GetTopReferrers(ctx context.Context, urlID string, limit int) ([]model.ReferrerStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopReferrers", ctx, urlID, limit)
	ret0, _ := ret[0].([]model.ReferrerStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopReferrers indicates an expected call of GetTopReferrers.
func (mr *MockClickEventQueryRepositoryMockRecorder) GetTopReferrers(ctx, urlID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopReferrers", reflect.TypeOf((*MockClickEventQueryRepository)(nil).GetTopReferrers), ctx, urlID, limit)
}
