// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/katatrina/url-shortener/internal/service (interfaces: URLRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_url_repository.go -package mock github.com/katatrina/url-shortener/internal/service URLRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/katatrina/url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockURLRepository) CountByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockURLRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockURLRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockURLRepository) Create(ctx context.Context, url model.URL) (*model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, url)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLRepositoryMockRecorder) Create(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLRepository)(nil).Create), ctx, url)
}

// Delete mocks base method.
func (m *MockURLRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLRepository)(nil).Delete), ctx, id)
}

// FindByShortCode mocks base method.
func (m *MockURLRepository) FindByShortCode(ctx context.Context, shortCode string) (*model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockURLRepositoryMockRecorder) FindByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockURLRepository)(nil).FindByShortCode), ctx, shortCode)
}

// IncrementClickCount mocks base method.
func (m *MockURLRepository) IncrementClickCount(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementClickCount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementClickCount indicates an expected call of IncrementClickCount.
func (mr *MockURLRepositoryMockRecorder) IncrementClickCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementClickCount", reflect.TypeOf((*MockURLRepository)(nil).IncrementClickCount), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockURLRepository) ListByUserID(ctx context.Context, userID string, limit, offset int) ([]model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockURLRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockURLRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// ShortCodeExists mocks base method.
func (m *MockURLRepository) ShortCodeExists(ctx context.Context, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortCodeExists", ctx, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortCodeExists indicates an expected call of ShortCodeExists.
func (mr *MockURLRepositoryMockRecorder) ShortCodeExists(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortCodeExists", reflect.TypeOf((*MockURLRepository)(nil).ShortCodeExists), ctx, shortCode)
}
